name: Java CD/CI with Maven

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install --file pom.xml
      
      # Install Elastic Beanstalk CLI (eb CLI)
    - name: Install Elastic Beanstalk CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awsebcli --upgrade
        
    - name: Login AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  
        
    # Initialize Elastic Beanstalk environment (only needed once, you can remove after first setup)
    - name: Initialize Elastic Beanstalk Environment
      run: |
        eb init -p java-17 --region us-east-1 demo  # Replace with your region and app name
        eb use Teste-env  # Replace with your environment name

    # Deploy to Elastic Beanstalk
    - name: Deploy to AWS Elastic Beanstalk
      run: eb deploy
